<?php

namespace TicTacToe\application\model\Entities;

use Doctrine\ORM\EntityRepository;

/**
 * GameRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class GameRepository extends EntityRepository
{
}
