<?php

namespace models\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * GameRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class GameTypeRepository extends EntityRepository
{
}
