<?php

namespace models\Repositories;

use Illuminate\Support\Collection;

/**
 * GameRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class GameTypeRepository extends BaseRepository
{
}
