<?php

namespace models\Repositories;

/**
 * PlayerRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class PlayerRepository extends BaseRepository
{
}
